[workspace]
resolver = "2"
members = ["crates/linkport", "crates/linkport-core", "crates/linkport-win"]

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT"
authors = ["Hendry Chou"]

[workspace.dependencies]
linkport-core = { path = "crates/linkport-core" }
linkport-win = { path = "crates/linkport-win" }
anyhow = "1"
axum = "0.8"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
dirs = "5"
getrandom = "0.2"
globset = "0.4"
regex = "1"
rust-embed = "8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }
toml = "0.8"
tower-http = { version = "0.6", features = ["cors"] }
tray-icon = "0.19"
ureq = "2"
url = "2"
windows-sys = { version = "0.59", features = [
  "Win32_Foundation",
  "Win32_System_DataExchange",
  "Win32_System_Memory",
  "Win32_System_Threading",
  "Win32_UI_WindowsAndMessaging",
] }
winreg = "0.52"

[profile.release]
lto = "thin"
strip = true
